<li>
          <div class="gw-box">
            <div class="gw-img"> <a href="[field:arcurl/]" title="[field:title /]" target="_blank"><img src="[field:litpic/]" alt="[field:title /]"></a> </div>
            <div class="gw-text"> <a href="[field:arcurl/]" title="[field:title /]" target="_blank">
              <h4>[field:title /]<em>[field:tel /]</em></h4>
              </a>
              <p>[field:description function="cn_substr(@me,180)"/]...</p>
              <div class="gw-foot"> <a href="[field:arcurl/]" title="[field:title /]" target="_blank">进入主页</a> </div>
            </div>
          </div>
        </li>