<?php
$z[0]=Array("global","(@me > 4)?@me=\"img-box-right\":@me=\"img-box-top\";",42,147);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",159,174);
$z[1][4]=array();
$z[2]=Array("title","",183,198);
$z[2][4]=array();
$z[3]=Array("litpic","",235,250);
$z[3][4]=array();
$z[4]=Array("title","",257,272);
$z[4][4]=array();
$z[5]=Array("arcurl","",305,320);
$z[5][4]=array();
$z[6]=Array("title","",329,344);
$z[6][4]=array();
$z[7]=Array("title","",346,361);
$z[7][4]=array();

?>