<?php
$z[0]=Array("global","if(@me==1){@me = \"active\";}else{@me = \"display: none;\";}",11,124);
$z[0][4]=array();
$z[0][4]['name']="itemindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","",150,174);
$z[1][4]=array();
$z[1][4]['name']="itemindex";
$z[2]=Array("field","",187,215);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",246,275);
$z[3][4]=array();
$z[3][4]['name']="typename";

?>