<li>
            <div class="style1"><a target="_blank" href="[field:arcurl/]"><img src="[field:picname/]" alt="[field:title/]" /></a></div>
            <div class="style2"><a href="[field:arcurl/]" target="_blank">[field:title/]</a>
              <p class="desc">[field:description/]...<a target="_blank" href="[field:arcurl/]" class="style1">[µã»÷ÔÄ¶Á]</a></p>
              <p class="info">ÈÕÆÚ:<span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>ÔÄ¶Á:<span>[field:click/]</span></p>
            </div>
          </li>