<li>
          <div class="news_list-box">
            <div class="news_list-title"> <a href="[field:arcurl/]" title="[field:title /]" target="_blank">
              <h4>[field:title /]</h4>
              </a> </div>
            <div class="news_list-text">
              <p> [field:description function="cn_substr(@me,120)"/]... </p>
            </div>
            <div class="news_list-foot"> <a href="[field:arcurl/]" target="_blank">了解更多</a> <a href="http://wpa.qq.com/msgrd?v=3&amp;uin=[field:global.cfg_qq/]&amp;site=qq&amp;menu=yes" target="blank">点击咨询</a>
              <div class="clear"></div>
            </div>
          </div>
        </li>