<div class="new_left_box">
        <div class="new_left_box_img"> <a href="[field:arcurl/]" title="[field:title /]"><img src="[field:litpic/]" alt="[field:title /]" /></a> </div>
        <div class="new_left_box_text"> <a href="[field:arcurl/]" title="[field:title /]">
          <h4>[field:title /]</h4>
          </a>
          <p>[field:description function="cn_substr(@me,120)"/]...<a href="[field:arcurl/]" title="[field:title /]">  [详情]</a></p>
          <div class="link_1"> <a href="[field:arcurl/]" class="ckgd">查看更多</a> <span class="question"><a href='[field:typeurl/]' target="_blank">[field:typename/]</a></span> <span class="stars">[field:click/]</span> <span class="date2">[field:pubdate function="GetDateMK(@me)"/]</span> </div>
        </div>
        <div class="clear"></div>
      </div>