<?php
$z[0]=Array("global","(@me > 4)?@me=\"img-box-bottom-right\":@me=\"img-box-bottom\";",43,158);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",170,185);
$z[1][4]=array();
$z[2]=Array("title","",194,209);
$z[2][4]=array();
$z[3]=Array("litpic","",246,261);
$z[3][4]=array();
$z[4]=Array("title","",268,283);
$z[4][4]=array();
$z[5]=Array("arcurl","",316,331);
$z[5][4]=array();
$z[6]=Array("title","",340,355);
$z[6][4]=array();
$z[7]=Array("title","",357,372);
$z[7][4]=array();

?>