<li>
          <div class="img-child-box  [field:global runphp='yes' name=autoindex](@me > 4)?@me="img-box-bottom-right":@me="img-box-bottom";[/field:global]"> <a href="[field:arcurl/]" title="[field:title /]"><img width="580" height="380" src="[field:litpic/]" alt="[field:title /]"/></a>
            <p><a href="[field:arcurl/]" title="[field:title /]">[field:title /]</a></p>
          </div>
        </li>