<?php
$z[0]=Array("field","",251,270);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",271,297);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",337,366);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",405,463);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",862,899);
$z[4][4]=array();
$z[4][4]['filename']="header.htm";
$z[5]=Array("field","",988,1010);
$z[5][4]=array();
$z[5][4]['name']="typename";
$z[6]=Array("field","",1094,1115);
$z[6][4]=array();
$z[6][4]['name']="content";
$z[7]=Array("channel","\n          <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\n          ",1308,1526);
$z[7][4]=array();
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<li class=\"current\"><a href=\"~typelink~\">~typename~</a></li>";
$z[8]=Array("arclist","\n        <li><a href=\"[field:arcurl/]\" target=\"_blank\"><span>[field:title/]</span><img src=\"[field:picname/]\" width=\"250\" height=\"182\" alt=\"[field:title/]\" /></a></li>\n        ",2048,2282);
$z[8][4]=array();
$z[8][4]['typeid']="1";
$z[8][4]['titlelen']="42";
$z[8][4]['row']="3";
$z[9]=Array("include","",2442,2479);
$z[9][4]=array();
$z[9][4]['filename']="footer.htm";

?>