<li>
          <div class="gw-box">
            <div class="gw-img"> <a href="[field:arcurl/]" title="[field:title /]" target="_blank"><img src="[field:litpic/]" alt="[field:title /]" /></a> </div>
            <div class="gw-text"> <a href="[field:arcurl/]" title="[field:title /]" target="_blank">
              <h4>[field:title /]<em>[field:typename/]</em></h4>
              </a>
              <p>[field:description function="cn_substr(@me,120)"/]...</p>
              <div class="gw-foot"> <span>
                <p>[field:tel /]</p>
                </span> <a href="http://wpa.qq.com/msgrd?v=3&uin=[field:global.cfg_qq/]&site=qq&menu=yes" target="blank">立即咨询</a> </div>
            </div>
          </div>
        </li>