<dl>
          <dt><a href="[field:arcurl/]" title="[field:title /]"><img  src="[field:litpic/]" alt="[field:title /]"/></a></dt>
          <dd>
            <h5><a href="[field:arcurl/]" title="[field:title /]">[field:title /]</a></h5>
            <p>[field:description function="cn_substr(@me,230)"/]...</p>
            <div class="link_1"> <span class="question"><a href='[field:typeurl/]' target="_blank">[field:typename/]</a></span> <span class="stars">[field:click/]</span> <span class="date2">[field:pubdate function="GetDateMK(@me)"/]</span> </div>
          </dd>
        </dl>