<?php
$z[0]=Array("global","(@me > 4)?@me=\"img-box-right\":@me=\"img-box-top\";",42,147);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",158,173);
$z[1][4]=array();
$z[2]=Array("title","",182,197);
$z[2][4]=array();
$z[3]=Array("litpic","",234,249);
$z[3][4]=array();
$z[4]=Array("title","",256,271);
$z[4][4]=array();
$z[5]=Array("arcurl","",304,319);
$z[5][4]=array();
$z[6]=Array("title","",328,343);
$z[6][4]=array();
$z[7]=Array("title","",345,360);
$z[7][4]=array();

?>