<?php
$z[0]=Array("global","",87,109);
$z[0][4]=array();
$z[0][4]['name']="cfg_tel";
$z[1]=Array("global","",232,254);
$z[1][4]=array();
$z[1][4]['name']="cfg_tel";
$z[2]=Array("type","\r\n    <li><a href=\"list.php?tid=[field:id/]\"><img src=\"/m/style/images/map.png\" alt=\"\">\r\n      <p>[field:typename /]</p>\r\n      </a></li>\r\n    ",360,538);
$z[2][4]=array();
$z[2][4]['typeid']="29";
$z[3]=Array("global","",787,809);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",899,920);
$z[4][4]=array();
$z[4][4]['name']="cfg_qq";

?>