<?php
$z[0]=Array("field","",266,285);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",286,312);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",353,382);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",422,480);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",879,916);
$z[4][4]=array();
$z[4][4]['filename']="header.htm";
$z[5]=Array("field","",979,1008);
$z[5][4]=array();
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",1319,1532);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";
$z[7]=Array("list","\r\n        <li><a href=\"[field:arcurl/]\" target=\"_blank\"><span>[field:title/]</span><img src=\"[field:picname/]\" width=\"310\" height=\"240\" alt=\"[field:title/]\" /></a></li>\r\n        ",1608,1822);
$z[7][4]=array();
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",1894,1972);
$z[8][4]=array();
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2017,2060);
$z[9][4]=array();
$z[9][4]['filename']="footer_index.htm";

?>