<?php
$z[0]=Array("arclist","\r\n      <li><a href=\"[field:arcurl/]\" title=\"[field:title /]\" target=\"_blank\">[field:title /]</a></li>\r\n      ",2038,2212);
$z[0][4]=array();
$z[0][4]['titlelen']="45";
$z[0][4]['row']="5";
$z[0][4]['typeid']="all";
$z[1]=Array("global","",2371,2392);
$z[1][4]=array();
$z[1][4]['name']="cfg_mc";
$z[2]=Array("global","",2418,2440);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",2463,2486);
$z[3][4]=array();
$z[3][4]['name']="cfg_telz";
$z[4]=Array("global","",2509,2532);
$z[4][4]=array();
$z[4][4]['name']="cfg_addz";

?>